---
- hosts: localhost
  tasks:
    - package:
        name: tree
    - shell: "tree {{ playbook_dir }}/../"
      register: myvar
    - copy:
        content: "{{ myvar }}"
        dest: "/tmp/tmp_tree"
...
